# Generated by Django 4.1.5 on 2023-02-24 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0001_initial'),
        ('statistika', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistika',
            name='ombor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vault.ombor'),
        ),
    ]
