# Generated by Django 4.1.5 on 2023-02-21 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ombor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=500)),
                ('tel', models.PositiveIntegerField()),
                ('ism', models.CharField(max_length=150)),
                ('manzil', models.CharField(max_length=1000)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mahsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('brend', models.CharField(max_length=200)),
                ('narx', models.PositiveIntegerField()),
                ('kelgan_sana', models.DateField()),
                ('miqdor', models.PositiveIntegerField()),
                ('olchov', models.CharField(max_length=500)),
                ('ombor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vault.ombor')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=150)),
                ('nom', models.CharField(max_length=150)),
                ('manzil', models.CharField(max_length=500)),
                ('tel', models.PositiveIntegerField()),
                ('qarz', models.PositiveIntegerField()),
                ('ombor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vault.ombor')),
            ],
        ),
    ]
